excluded: # paths to ignore during linting. Takes precedence over `included`.

line_length:
  warning: 180
  error: 180
  ignores_comments: true

identifier_name:
   excluded: # excluded via string array
    - id
    - URL
    - ui
    - ok